#include "bgfx_scene_textures.h"

namespace rhythm::render::detail {
BgfxSceneTextures::BgfxSceneTextures() {
    constexpr std::array names{"s_scene_base", "s_scene_normal", "s_scene_orm", "s_scene_emission"};
    for (std::size_t i = 0; i < names.size(); ++i)
        samplers_[i] = GpuHandle(bgfx::createUniform(names[i], bgfx::UniformType::Sampler));
    enabled_ = GpuHandle(bgfx::createUniform("u_scene_textures", bgfx::UniformType::Vec4));
    options_ = GpuHandle(bgfx::createUniform("u_scene_texture_options", bgfx::UniformType::Vec4));
    uv_ = GpuHandle(bgfx::createUniform("u_scene_uv", bgfx::UniformType::Vec4));
    constexpr std::uint32_t kWhite = 0xffffffff;
    white_ = GpuHandle(bgfx::createTexture2D(1, 1, false, 1, bgfx::TextureFormat::RGBA8, 0,
                                             bgfx::copy(&kWhite, sizeof(kWhite))));
}
void BgfxSceneTextures::Bind(const MaterialTextures& textures,
                             const SceneTextureResolver& resolve) const {
    std::array<float, 4> enabled{};
    for (std::uint8_t i = 0; i < 4; ++i) {
        const bool present = textures.slots_[i].device_ != 0;
        enabled[i] = present ? 1.0f : 0.0f;
        // Explicit zero sampler flags select repeat and bilinear sampling for
        // both uploaded assets and textures generated by earlier graph passes.
        bgfx::setTexture(i, samplers_[i].Get(),
                         present ? resolve(textures.slots_[i]) : white_.Get(), 0);
    }
    const std::array options{textures.color_srgb_ ? 1.0f : 0.0f, textures.normal_scale_, 0.0f,
                             0.0f};
    bgfx::setUniform(enabled_.Get(), enabled.data());
    bgfx::setUniform(options_.Get(), options.data());
    bgfx::setUniform(uv_.Get(), textures.uv_transform_.data());
}
}  // namespace rhythm::render::detail
