#include "point_descriptors.h"

namespace rhythm::graph {
void AppendPointDescriptors(std::vector<OperatorDescriptor>& operators) {
    using Type = ValueType;
    operators.push_back({"gpu.particles",
                         Operation::kGpuParticleEmitter,
                         Type::kGpuPoints,
                         {{"emission", Type::kScalar, false},
                          {"burst", Type::kScalar, false},
                          {"flow_strength", Type::kScalar, false}},
                         {{"particle_capacity", 65536.0, 1, 262144, {}, true},
                          {"seed", 1.0, 0, 16777215, {}, true},
                          {"initial_fill", 1.0, 0, 1},
                          {"emission_rate", 16000.0, 0, 262144},
                          {"emission", 1.0, 0, 100},
                          {"burst", 0.0, 0, 262144, {}, true},
                          {"lifetime", 4.0, 0.05, 120},
                          {"center_x", 0.5, -4, 4},
                          {"center_y", 0.5, -4, 4},
                          {"emitter_radius", 0.3, 0, 4},
                          {"particle_speed", 0.08, 0, 8},
                          {"drag", 0.1, 0, 1},
                          {"gravity_x", 0.0, -8, 8},
                          {"gravity_y", 0.0, -8, 8},
                          {"flow_strength", 0.1, 0, 8},
                          {"flow_frequency", 8.0, 0, 100},
                          {"flow_evolution", 0.3, 0, 8},
                          {"point_size", 0.002, 0, 1},
                          {"color_a", Color{0.05, 0.6, 1, 0.2}},
                          {"color_b", Color{1, 0.1, 0.4, 0.2}}},
                         true});
    operators.push_back({"gpu.render",
                         Operation::kGpuPointRender,
                         Type::kTexture,
                         {{"points", Type::kGpuPoints}, {"opacity", Type::kScalar, false}},
                         {{"opacity", 1.0, 0, 1},
                          {"point_blend", 1.0, 0, 1, {"composite.over", "composite.add"}}}});

    operators.push_back({"point.physics2d",
                         Operation::kPointPhysics,
                         Type::kPoints,
                         {{"points", Type::kPoints},
                          {"gravity_x", Type::kScalar, false},
                          {"gravity_y", Type::kScalar, false}},
                         {{"gravity_x", 0.0, -10, 10},
                          {"gravity_y", 0.98, -10, 10},
                          {"body_shape", 0.0, 0, 1, {"physics.circle", "physics.box"}},
                          {"restitution", 0.6, 0, 1},
                          {"friction", 0.3, 0, 1},
                          {"density", 1.0, 0.001, 100},
                          {"physics_bounds",
                           2.0,
                           0,
                           2,
                           {"physics.unbounded", "physics.floor", "physics.box_bounds"}}},
                         true});
    operators.push_back({"point.grid",
                         Operation::kPointGrid,
                         Type::kPoints,
                         {},
                         {{"columns", 16.0, 1, 128, {}, true},
                          {"rows", 9.0, 1, 128, {}, true},
                          {"point_size", 0.012, 0, 1},
                          {"grid_width", 0.8, 0, 4},
                          {"grid_height", 0.8, 0, 4},
                          {"center_x", 0.5, -4, 4},
                          {"center_y", 0.5, -4, 4},
                          {"color_a", Color{0.1, 0.8, 1, 1}}}});
    operators.push_back(
            {"point.emitter",
             Operation::kParticleEmitter,
             Type::kPoints,
             {{"emission", Type::kScalar, false},
              {"burst", Type::kScalar, false},
              {"flow_strength", Type::kScalar, false}},
             {{"particle_capacity", 2048.0, 1, 16384, {}, true},
              {"seed", 1.0, 0, 4294967295.0, {}, true},
              {"emission_rate", 120.0, 0, 20000},
              {"emission", 1.0, 0, 100},
              {"burst", 0.0, 0, 16384, {}, true},
              {"lifetime", 3.0, 0.05, 60},
              {"lifetime_variation", 0.5, 0, 0.95},
              {"emitter_shape", 0.0, 0, 2, {"emitter.rectangle", "emitter.disk", "emitter.ring"}},
              {"center_x", 0.5, -4, 4},
              {"center_y", 0.7, -4, 4},
              {"emitter_width", 0.1, 0, 4},
              {"emitter_height", 0.05, 0, 4},
              {"direction", -90.0, -360, 360},
              {"spread", 30.0, 0, 360},
              {"particle_speed", 0.3, 0, 10},
              {"speed_variation", 0.67, 0, 1},
              {"gravity_x", 0.0, -20, 20},
              {"gravity_y", 0.1, -20, 20},
              {"flow_strength", 0.0, 0, 2},
              {"flow_frequency", 3.0, 0.25, 12},
              {"flow_evolution", 0.15, 0, 2},
              {"point_size", 0.015, 0, 1},
              {"size_variation", 0.67, 0, 1},
              {"angular_speed", 1.0, 0, 100},
              {"fade_in", 0.05, 0, 1},
              {"fade_out", 0.25, 0, 1},
              {"color_a", Color{0.1, 0.8, 1, 1}},
              {"color_b", Color{0.8, 0.1, 1, 0}}},
             true});
    operators.push_back({"point.transform",
                         Operation::kPointTransform,
                         Type::kPoints,
                         {{"points", Type::kPoints},
                          {"scale", Type::kScalar, false},
                          {"rotation", Type::kScalar, false},
                          {"opacity", Type::kScalar, false}},
                         {{"scale", 1.0, 0, 8},
                          {"rotation", 0.0, -36000, 36000},
                          {"translate_x", 0.0, -4, 4},
                          {"translate_y", 0.0, -4, 4},
                          {"opacity", 1.0, 0, 1}}});
    operators.push_back({"point.render",
                         Operation::kPointRender,
                         Type::kTexture,
                         {{"points", Type::kPoints}, {"sprite", Type::kTexture, false}},
                         {{"point_style", 0.0, 0, 1, {"point.soft_circle", "point.square"}},
                          {"point_blend", 0.0, 0, 1, {"composite.over", "composite.add"}}}});
}
}  // namespace rhythm::graph
