#include "scene_descriptors.h"

namespace rhythm::graph {
void AppendSceneDescriptors(std::vector<OperatorDescriptor>& operators) {
    using Type = ValueType;
    operators.push_back({"material.shader",
                         Operation::kMaterialShader,
                         Type::kMaterial,
                         {{"material", Type::kMaterial},
                          {"time", Type::kScalar, false},
                          {"a", Type::kScalar, false},
                          {"b", Type::kScalar, false},
                          {"c", Type::kScalar, false},
                          {"d", Type::kScalar, false}},
                         {{"asset", assets::AssetId{}},
                          {"a", 0.0, -1e6, 1e6},
                          {"b", 0.0, -1e6, 1e6},
                          {"c", 0.0, -1e6, 1e6},
                          {"d", 0.0, -1e6, 1e6}},
                         true});
    operators.push_back({"scene.environment",
                         Operation::kSceneEnvironment,
                         Type::kScene,
                         {{"scene", Type::kScene},
                          {"environment_texture", Type::kTexture},
                          {"environment_energy", Type::kScalar, false},
                          {"environment_rotation", Type::kScalar, false}},
                         {{"environment_enabled", 1.0, 0, 1, {"option.off", "option.on"}},
                          {"environment_energy", 1.0, 0, 100},
                          {"environment_rotation", 0.0, -36000, 36000},
                          {"environment_srgb", 1.0, 0, 1, {"option.off", "option.on"}}}});
    operators.push_back({"scene.shadow",
                         Operation::kSceneShadow,
                         Type::kScene,
                         {{"scene", Type::kScene}},
                         {{"shadow_enabled", 1.0, 0, 1, {"option.off", "option.on"}},
                          {"shadow_light", 0.0, 0, 3, {}, true},
                          {"shadow_resolution",
                           2.0,
                           0,
                           3,
                           {"shadow.256", "shadow.512", "shadow.1024", "shadow.2048"}},
                          {"shadow_extent", 10.0, 0.1, 10000},
                          {"shadow_distance", 20.0, 0.1, 10000},
                          {"shadow_near", 0.05, 0.001, 1000},
                          {"shadow_center_x", 0.0, -10000, 10000},
                          {"shadow_center_y", 0.0, -10000, 10000},
                          {"shadow_center_z", 0.0, -10000, 10000},
                          {"shadow_bias", 0.001, 0, 0.05},
                          {"shadow_normal_bias", 0.01, 0, 1},
                          {"shadow_filter", 1.0, 0, 1, {"option.off", "option.on"}}}});
    operators.push_back({"material.textures",
                         Operation::kMaterialTextures,
                         Type::kMaterial,
                         {{"material", Type::kMaterial},
                          {"base_texture", Type::kTexture, false},
                          {"normal_texture", Type::kTexture, false},
                          {"orm_texture", Type::kTexture, false},
                          {"emission_texture", Type::kTexture, false}},
                         {{"material_srgb", 1.0, 0, 1, {}, true},
                          {"normal_scale", 1.0, 0, 4},
                          {"uv_scale_x", 1.0, -100, 100},
                          {"uv_scale_y", 1.0, -100, 100},
                          {"uv_offset_x", 0.0, -10000, 10000},
                          {"uv_offset_y", 0.0, -10000, 10000}}});
    for (bool spot : {false, true}) {
        OperatorDescriptor light{spot ? "scene.spot_light" : "scene.point_light",
                                 spot ? Operation::kSpotLight : Operation::kPointLight,
                                 Type::kScene,
                                 {{"light_energy", Type::kScalar, false},
                                  {"translate_x", Type::kScalar, false},
                                  {"translate_y", Type::kScalar, false},
                                  {"translate_z", Type::kScalar, false}},
                                 {{"light_energy", 8.0, 0, 100},
                                  {"color_a", Color{1, 1, 1, 1}},
                                  {"translate_x", 0.0, -10000, 10000},
                                  {"translate_y", 2.0, -10000, 10000},
                                  {"translate_z", 3.0, -10000, 10000},
                                  {"light_range", 10.0, 0.01, 10000},
                                  {"light_decay", 2.0, 0, 4}}};
        if (spot) {
            light.inputs_.push_back({"spot_angle", Type::kScalar, false});
            light.properties_.insert(light.properties_.end(), {{"light_x", 0.0, -1, 1},
                                                               {"light_y", -0.5, -1, 1},
                                                               {"light_z", -1.0, -1, 1},
                                                               {"spot_angle", 45.0, 0.1, 89},
                                                               {"spot_decay", 1.0, 0.1, 16}});
        }
        operators.push_back(std::move(light));
    }
    operators.push_back({"scene.point_instances",
                         Operation::kPointInstances,
                         Type::kScene,
                         {{"geometry", Type::kGeometry},
                          {"points", Type::kPoints},
                          {"material", Type::kMaterial, false},
                          {"scale", Type::kScalar, false},
                          {"height", Type::kScalar, false},
                          {"audio_gain", Type::kScalar, false}},
                         {{"instance_limit", 1024.0, 1, 16384, {}, true},
                          {"instance_span", 10.0, 0.01, 100},
                          {"scale", 1.0, 0.001, 100},
                          {"height", 1.0, 0.001, 100},
                          {"audio_gain", 12.0, 0, 100},
                          {"instance_point_color", 0.0, 0, 1, {"option.off", "option.on"}}},
                         true});
    operators.push_back({"geometry.glb",
                         Operation::kGeometryGlb,
                         Type::kGeometry,
                         {},
                         {{"asset", assets::AssetId{}}}});
    operators.push_back({"material.pbr",
                         Operation::kMaterialPbr,
                         Type::kMaterial,
                         {{"metallic", Type::kScalar, false},
                          {"roughness", Type::kScalar, false},
                          {"emission", Type::kScalar, false}},
                         {{"color_a", Color{0.8, 0.3, 0.08, 1}},
                          {"metallic", 0.0, 0, 1},
                          {"roughness", 0.5, 0.05, 1},
                          {"emission", 0.0, 0, 100},
                          {"color_b", Color{1, 1, 1, 1}},
                          {"double_sided", 0.0, 0, 1, {"option.off", "option.on"}}}});
    operators.push_back({"scene.directional_light",
                         Operation::kDirectionalLight,
                         Type::kScene,
                         {{"light_energy", Type::kScalar, false}},
                         {{"light_x", 1.0, -1, 1},
                          {"light_y", 1.0, -1, 1},
                          {"light_z", 1.0, -1, 1},
                          {"light_energy", 3.0, 0, 100},
                          {"color_a", Color{1, 1, 1, 1}}}});
    operators.push_back({"geometry.cube", Operation::kGeometryCube, Type::kGeometry});
    operators.push_back({"geometry.torus",
                         Operation::kGeometryTorus,
                         Type::kGeometry,
                         {},
                         {{"radius", 0.8, 0.001, 100},
                          {"tube_ratio", 0.08, 0.01, 0.9},
                          {"radial_segments", 64.0, 3, 256, {}, true},
                          {"tube_segments", 16.0, 3, 128, {}, true}}});
    operators.push_back({"geometry.sphere",
                         Operation::kGeometrySphere,
                         Type::kGeometry,
                         {},
                         {{"radius", 0.5, 0.001, 100},
                          {"height", 1.0, 0.001, 100},
                          {"radial_segments", 32.0, 3, 256, {}, true},
                          {"rings", 16.0, 1, 128, {}, true}}});
    operators.push_back({"material.unlit",
                         Operation::kMaterialUnlit,
                         Type::kMaterial,
                         {},
                         {{"color_a", Color{0.1, 0.8, 1, 1}},
                          {"double_sided", 0.0, 0, 1, {"option.off", "option.on"}}}});
    operators.push_back({"scene.instance",
                         Operation::kSceneInstance,
                         Type::kScene,
                         {{"geometry", Type::kGeometry}, {"material", Type::kMaterial, false}}});
    operators.push_back({"scene.transform",
                         Operation::kSceneTransform,
                         Type::kScene,
                         {{"scene", Type::kScene},
                          {"rotation_x", Type::kScalar, false},
                          {"rotation_y", Type::kScalar, false},
                          {"rotation_z", Type::kScalar, false},
                          {"scale", Type::kScalar, false},
                          {"translate_x", Type::kScalar, false},
                          {"translate_y", Type::kScalar, false},
                          {"translate_z", Type::kScalar, false},
                          {"scale_x", Type::kScalar, false},
                          {"scale_y", Type::kScalar, false},
                          {"scale_z", Type::kScalar, false}},
                         {{"rotation_x", 0.0, -36000, 36000},
                          {"rotation_y", 0.0, -36000, 36000},
                          {"rotation_z", 0.0, -36000, 36000},
                          {"scale", 1.0, 0.001, 100},
                          {"translate_x", 0.0, -1000, 1000},
                          {"translate_y", 0.0, -1000, 1000},
                          {"translate_z", 0.0, -1000, 1000},
                          {"scale_x", 1.0, 0.001, 100},
                          {"scale_y", 1.0, 0.001, 100},
                          {"scale_z", 1.0, 0.001, 100}}});
    operators.push_back({"scene.merge",
                         Operation::kSceneMerge,
                         Type::kScene,
                         {{"a", Type::kScene}, {"b", Type::kScene}}});
    operators.push_back({"scene.camera",
                         Operation::kSceneCamera,
                         Type::kCamera,
                         {},
                         {{"eye_x", 0.0, -10000, 10000},
                          {"eye_y", 0.0, -10000, 10000},
                          {"eye_z", 3.0, -10000, 10000},
                          {"target_x", 0.0, -10000, 10000},
                          {"target_y", 0.0, -10000, 10000},
                          {"target_z", 0.0, -10000, 10000},
                          {"projection", 0.0, 0, 1, {"camera.perspective", "camera.orthographic"}},
                          {"field_of_view", 60.0, 1, 179},
                          {"orthographic_height", 2.0, 0.001, 10000},
                          {"near_plane", 0.05, 0.001, 10000},
                          {"far_plane", 1000.0, 0.002, 100000}}});
    operators.push_back(
            {"scene.render",
             Operation::kSceneRender,
             Type::kTexture,
             {{"scene", Type::kScene}, {"camera", Type::kCamera, false}},
             {{"scene_antialiasing", 0.0, 0, 1, {"scene.aa_none", "scene.aa_supersample_2x"}}}});
}
}  // namespace rhythm::graph
