add_library(model_assets STATIC prepare.cpp)
target_include_directories(model_assets PUBLIC include PRIVATE "${PROJECT_SOURCE_DIR}/third_party/sources/picosha2")
target_link_libraries(model_assets PUBLIC runtime_package scene3d foundation_async PRIVATE model_import asset_store)
rhythm_project_target(model_assets)
if(BUILD_TESTING)
    add_executable(model_asset_tests tests/prepare_tests.cpp)
    target_include_directories(model_asset_tests PRIVATE "${PROJECT_SOURCE_DIR}/third_party/sources/picosha2")
    target_link_libraries(model_asset_tests PRIVATE prepared_assets asset_store)
    rhythm_project_target(model_asset_tests)
    add_test(NAME model_assets COMMAND model_asset_tests "${PROJECT_SOURCE_DIR}/third_party/assets/khronos-box/Box.glb" "${PROJECT_BINARY_DIR}/model-asset-tests")
    if(WIN32)
        set_tests_properties(model_assets PROPERTIES ENVIRONMENT_MODIFICATION
            "PATH=path_list_prepend:${RHYTHM_IO_SDK}/bin;PATH=path_list_prepend:${RHYTHM_IO_SDK}/debug/bin")
    endif()
endif()
