add_library(image_shader STATIC source.cpp artifact.cpp program.cpp)
target_include_directories(image_shader PUBLIC include)
if(ANDROID)
    set(image_shader_triplet arm64-android)
else()
    set(image_shader_triplet x64-windows)
endif()
find_path(RHYTHM_STB_LEXER_INCLUDE stb_c_lexer.h PATHS
    "C:/source/vcpkg/installed/${image_shader_triplet}/include"
    NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH REQUIRED)
target_include_directories(image_shader SYSTEM PRIVATE "${RHYTHM_STB_LEXER_INCLUDE}")
rhythm_project_target(image_shader)
if(BUILD_TESTING)
    add_executable(image_shader_program_tests tests/program_tests.cpp)
    target_link_libraries(image_shader_program_tests PRIVATE image_shader)
    rhythm_project_target(image_shader_program_tests)
    add_executable(image_shader_source_tests tests/source_tests.cpp)
    target_link_libraries(image_shader_source_tests PRIVATE image_shader)
    rhythm_project_target(image_shader_source_tests)
    add_test(NAME image_shader_source COMMAND image_shader_source_tests)
endif()
