add_library(image_shader STATIC source.cpp artifact.cpp program.cpp)
target_include_directories(image_shader PUBLIC include)
target_link_libraries(image_shader PUBLIC shader_expression shader_artifact)
rhythm_project_target(image_shader)
if(BUILD_TESTING)
    add_executable(image_shader_program_tests tests/program_tests.cpp)
    target_link_libraries(image_shader_program_tests PRIVATE image_shader)
    rhythm_project_target(image_shader_program_tests)
    add_executable(image_shader_source_tests tests/source_tests.cpp)
    target_link_libraries(image_shader_source_tests PRIVATE image_shader)
    rhythm_project_target(image_shader_source_tests)
    add_test(NAME image_shader_source COMMAND image_shader_source_tests)
endif()
