add_library(video_playback STATIC playback.cpp)
target_include_directories(video_playback PUBLIC include)
target_link_libraries(video_playback PUBLIC media_video)
rhythm_project_target(video_playback)
if(BUILD_TESTING)
    add_executable(video_playback_tests tests/playback_tests.cpp)
    target_link_libraries(video_playback_tests PRIVATE video_playback)
    rhythm_project_target(video_playback_tests)
    if(WIN32)
        add_test(NAME video_playback_fixtures COMMAND "${Python3_EXECUTABLE}"
            "${CMAKE_CURRENT_SOURCE_DIR}/../../tools/create-video-fixtures.py" "${PROJECT_BINARY_DIR}/video-playback-fixtures")
        set_tests_properties(video_playback_fixtures PROPERTIES FIXTURES_SETUP video_playback_media)
        add_test(NAME video_playback COMMAND video_playback_tests "${PROJECT_BINARY_DIR}/video-playback-fixtures")
        set_tests_properties(video_playback PROPERTIES FIXTURES_REQUIRED video_playback_media TIMEOUT 60)
    endif()
endif()
