add_library(media_arrangement STATIC audio_arrangement.cpp)
target_include_directories(media_arrangement PUBLIC include)
target_link_libraries(media_arrangement PUBLIC parameters asset_types storage_types)
rhythm_project_target(media_arrangement)
if(BUILD_TESTING)
    add_executable(audio_arrangement_tests tests/audio_arrangement_tests.cpp)
    target_link_libraries(audio_arrangement_tests PRIVATE media_arrangement)
    rhythm_project_target(audio_arrangement_tests)
    add_test(NAME audio_arrangement COMMAND audio_arrangement_tests)
endif()
