schema_version: 4
id: "p4-resonant-armillary"
revision: 100
nodes {
    id: 2
    type_key: "core.time"
    schema_version: 1
}
nodes {
    id: 3
    type_key: "audio.band"
    schema_version: 1
    properties {
        key: "audio_band"
        value {
            scalar: 12
        }
    }
    properties {
        key: "audio_channel"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 4
    type_key: "scalar.map"
    schema_version: 1
    properties {
        key: "input_max"
        value {
            scalar: 0.15
        }
    }
    properties {
        key: "input_min"
        value {
            scalar: 0
        }
    }
    properties {
        key: "map_mode"
        value {
            scalar: 0
        }
    }
    properties {
        key: "output_max"
        value {
            scalar: 110
        }
    }
    properties {
        key: "output_min"
        value {
            scalar: 25
        }
    }
}
nodes {
    id: 5
    type_key: "audio.band"
    schema_version: 1
    properties {
        key: "audio_band"
        value {
            scalar: 48
        }
    }
    properties {
        key: "audio_channel"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 6
    type_key: "audio.feature"
    schema_version: 1
    properties {
        key: "audio_feature"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 7
    type_key: "scalar.math"
    schema_version: 1
    properties {
        key: "a"
        value {
            scalar: 0
        }
    }
    properties {
        key: "b"
        value {
            scalar: 1
        }
    }
    properties {
        key: "math_mode"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 8
    type_key: "scalar.map"
    schema_version: 1
    properties {
        key: "input_max"
        value {
            scalar: 0.4
        }
    }
    properties {
        key: "input_min"
        value {
            scalar: 0
        }
    }
    properties {
        key: "map_mode"
        value {
            scalar: 0
        }
    }
    properties {
        key: "output_max"
        value {
            scalar: 1.5
        }
    }
    properties {
        key: "output_min"
        value {
            scalar: 0.08
        }
    }
}
nodes {
    id: 9
    type_key: "material.pbr"
    schema_version: 1
    properties {
        key: "color_a"
        value {
            color {
                r: 0.85490196943283081
                g: 0.69019609689712524
                b: 0.47450980544090271
                a: 1
            }
        }
    }
    properties {
        key: "color_b"
        value {
            color {
                r: 0.98039215803146362
                g: 0.78039216995239258
                b: 0.53333336114883423
                a: 1
            }
        }
    }
    properties {
        key: "double_sided"
        value {
            scalar: 0
        }
    }
    properties {
        key: "emission"
        value {
            scalar: 0
        }
    }
    properties {
        key: "metallic"
        value {
            scalar: 0.65
        }
    }
    properties {
        key: "roughness"
        value {
            scalar: 0.22
        }
    }
}
nodes {
    id: 10
    type_key: "material.pbr"
    schema_version: 1
    properties {
        key: "color_a"
        value {
            color {
                r: 0.16862745583057404
                g: 0.658823549747467
                b: 0.72156864404678345
                a: 1
            }
        }
    }
    properties {
        key: "color_b"
        value {
            color {
                r: 0.39215686917304993
                g: 0.86274510622024536
                b: 0.90196079015731812
                a: 1
            }
        }
    }
    properties {
        key: "double_sided"
        value {
            scalar: 0
        }
    }
    properties {
        key: "emission"
        value {
            scalar: 0
        }
    }
    properties {
        key: "metallic"
        value {
            scalar: 0.5
        }
    }
    properties {
        key: "roughness"
        value {
            scalar: 0.25
        }
    }
}
nodes {
    id: 11
    type_key: "geometry.torus"
    schema_version: 1
    properties {
        key: "radial_segments"
        value {
            scalar: 96
        }
    }
    properties {
        key: "radius"
        value {
            scalar: 1
        }
    }
    properties {
        key: "tube_ratio"
        value {
            scalar: 0.06
        }
    }
    properties {
        key: "tube_segments"
        value {
            scalar: 24
        }
    }
}
nodes {
    id: 12
    type_key: "scene.instance"
    schema_version: 1
}
nodes {
    id: 13
    type_key: "scene.transform"
    schema_version: 1
    properties {
        key: "rotation_x"
        value {
            scalar: 0
        }
    }
    properties {
        key: "rotation_y"
        value {
            scalar: 0
        }
    }
    properties {
        key: "rotation_z"
        value {
            scalar: 0
        }
    }
    properties {
        key: "scale"
        value {
            scalar: 1
        }
    }
    properties {
        key: "scale_x"
        value {
            scalar: 1
        }
    }
    properties {
        key: "scale_y"
        value {
            scalar: 1
        }
    }
    properties {
        key: "scale_z"
        value {
            scalar: 1
        }
    }
    properties {
        key: "translate_x"
        value {
            scalar: 0
        }
    }
    properties {
        key: "translate_y"
        value {
            scalar: 0
        }
    }
    properties {
        key: "translate_z"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 14
    type_key: "scene.instance"
    schema_version: 1
}
nodes {
    id: 15
    type_key: "scene.transform"
    schema_version: 1
    properties {
        key: "rotation_x"
        value {
            scalar: 70
        }
    }
    properties {
        key: "rotation_y"
        value {
            scalar: 0
        }
    }
    properties {
        key: "rotation_z"
        value {
            scalar: 0
        }
    }
    properties {
        key: "scale"
        value {
            scalar: 0.75
        }
    }
    properties {
        key: "scale_x"
        value {
            scalar: 1
        }
    }
    properties {
        key: "scale_y"
        value {
            scalar: 1
        }
    }
    properties {
        key: "scale_z"
        value {
            scalar: 1
        }
    }
    properties {
        key: "translate_x"
        value {
            scalar: 0
        }
    }
    properties {
        key: "translate_y"
        value {
            scalar: 0
        }
    }
    properties {
        key: "translate_z"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 16
    type_key: "scene.merge"
    schema_version: 1
}
nodes {
    id: 17
    type_key: "scene.directional_light"
    schema_version: 1
    properties {
        key: "color_a"
        value {
            color {
                r: 1
                g: 0.94117647409439087
                b: 0.85098040103912354
                a: 1
            }
        }
    }
    properties {
        key: "light_energy"
        value {
            scalar: 3
        }
    }
    properties {
        key: "light_x"
        value {
            scalar: 1
        }
    }
    properties {
        key: "light_y"
        value {
            scalar: 1
        }
    }
    properties {
        key: "light_z"
        value {
            scalar: 1
        }
    }
}
nodes {
    id: 18
    type_key: "scene.merge"
    schema_version: 1
}
nodes {
    id: 20
    type_key: "scene.camera"
    schema_version: 1
    properties {
        key: "eye_x"
        value {
            scalar: 0
        }
    }
    properties {
        key: "eye_y"
        value {
            scalar: 0
        }
    }
    properties {
        key: "eye_z"
        value {
            scalar: 3
        }
    }
    properties {
        key: "far_plane"
        value {
            scalar: 1000
        }
    }
    properties {
        key: "field_of_view"
        value {
            scalar: 60
        }
    }
    properties {
        key: "near_plane"
        value {
            scalar: 0.05
        }
    }
    properties {
        key: "orthographic_height"
        value {
            scalar: 3
        }
    }
    properties {
        key: "projection"
        value {
            scalar: 1
        }
    }
    properties {
        key: "target_x"
        value {
            scalar: 0
        }
    }
    properties {
        key: "target_y"
        value {
            scalar: 0
        }
    }
    properties {
        key: "target_z"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 21
    type_key: "scene.render"
    schema_version: 1
    properties {
        key: "scene_antialiasing"
        value {
            scalar: 1
        }
    }
    properties {
        key: "texture_precision"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 22
    type_key: "output.texture"
    schema_version: 1
}
nodes {
    id: 23
    type_key: "component.user.23"
    schema_version: 1
    properties {
        key: "rotation_x"
        value {
            scalar: 0
        }
    }
    properties {
        key: "rotation_y"
        value {
            scalar: 0
        }
    }
    properties {
        key: "rotation_z"
        value {
            scalar: -14.008285265643551
        }
    }
    properties {
        key: "scale"
        value {
            scalar: 0.9
        }
    }
    properties {
        key: "scale_x"
        value {
            scalar: 1
        }
    }
    properties {
        key: "scale_y"
        value {
            scalar: 1.121220292519671
        }
    }
    properties {
        key: "scale_z"
        value {
            scalar: 1
        }
    }
    properties {
        key: "translate_x"
        value {
            scalar: 0.52868843078613281
        }
    }
    properties {
        key: "translate_y"
        value {
            scalar: 0
        }
    }
    properties {
        key: "translate_z"
        value {
            scalar: 0
        }
    }
}
output: 22
canvas {
    width: 1280
    height: 720
}
signals {
    name: "n1"
    source: 2
}
signals {
    name: "n2"
    source: 3
}
signals {
    name: "n3"
    source: 4
}
signals {
    name: "n4"
    source: 5
}
signals {
    name: "n5"
    source: 6
}
signals {
    name: "n6"
    source: 7
}
signals {
    name: "n7"
    source: 8
}
signals {
    name: "n8"
    source: 9
}
signals {
    name: "n9"
    source: 10
}
signals {
    name: "n10"
    source: 11
}
signals {
    name: "n11"
    source: 12
}
signals {
    name: "n12"
    source: 13
}
signals {
    name: "n13"
    source: 14
}
signals {
    name: "n14"
    source: 15
}
signals {
    name: "n15"
    source: 16
}
signals {
    name: "n16"
    source: 17
}
signals {
    name: "n17"
    source: 18
}
signals {
    name: "n18"
    source: 23
}
signals {
    name: "n19"
    source: 20
}
signals {
    name: "n20"
    source: 21
}
signals {
    name: "n21"
    source: 22
}
bindings {
    node: 4
    input: "value"
    signal: "n2"
}
bindings {
    node: 7
    input: "a"
    signal: "n4"
}
bindings {
    node: 7
    input: "b"
    signal: "n5"
}
bindings {
    node: 8
    input: "value"
    signal: "n6"
}
bindings {
    node: 9
    input: "emission"
    signal: "n7"
}
bindings {
    node: 10
    input: "emission"
    signal: "n7"
}
bindings {
    node: 12
    input: "geometry"
    signal: "n10"
}
bindings {
    node: 12
    input: "material"
    signal: "n8"
}
bindings {
    node: 13
    input: "rotation_x"
    signal: "n1"
}
bindings {
    node: 13
    input: "rotation_y"
    signal: "n3"
}
bindings {
    node: 13
    input: "scene"
    signal: "n11"
}
bindings {
    node: 14
    input: "geometry"
    signal: "n10"
}
bindings {
    node: 14
    input: "material"
    signal: "n9"
}
bindings {
    node: 15
    input: "rotation_z"
    signal: "n1"
}
bindings {
    node: 15
    input: "scene"
    signal: "n13"
}
bindings {
    node: 16
    input: "a"
    signal: "n12"
}
bindings {
    node: 16
    input: "b"
    signal: "n14"
}
bindings {
    node: 18
    input: "a"
    signal: "n15"
}
bindings {
    node: 18
    input: "b"
    signal: "n16"
}
bindings {
    node: 23
    input: "scene"
    signal: "n17"
}
bindings {
    node: 21
    input: "camera"
    signal: "n19"
}
bindings {
    node: 21
    input: "scene"
    signal: "n18"
}
bindings {
    node: 22
    input: "source"
    signal: "n20"
}
components {
    type_key: "component.user.23"
    schema_version: 1
    nodes {
        id: 19
        type_key: "scene.transform"
        schema_version: 1
        properties {
            key: "rotation_x"
            value {
                scalar: 0
            }
        }
        properties {
            key: "rotation_y"
            value {
                scalar: 0
            }
        }
        properties {
            key: "rotation_z"
            value {
                scalar: -14.008285265643551
            }
        }
        properties {
            key: "scale"
            value {
                scalar: 0.9
            }
        }
        properties {
            key: "scale_x"
            value {
                scalar: 1
            }
        }
        properties {
            key: "scale_y"
            value {
                scalar: 1.121220292519671
            }
        }
        properties {
            key: "scale_z"
            value {
                scalar: 1
            }
        }
        properties {
            key: "translate_x"
            value {
                scalar: 0.52868843078613281
            }
        }
        properties {
            key: "translate_y"
            value {
                scalar: 0
            }
        }
        properties {
            key: "translate_z"
            value {
                scalar: 0
            }
        }
    }
    output: 19
    signals {
        name: "n18"
        source: 19
    }
    inputs {
        key: "scene"
        node: 19
        input: "scene"
    }
    parameters {
        key: "rotation_x"
        node: 19
        property: "rotation_x"
        group: "Armillary Composition"
    }
    parameters {
        key: "rotation_y"
        node: 19
        property: "rotation_y"
        group: "Armillary Composition"
    }
    parameters {
        key: "rotation_z"
        node: 19
        property: "rotation_z"
        group: "Armillary Composition"
    }
    parameters {
        key: "scale"
        node: 19
        property: "scale"
        group: "Armillary Composition"
    }
    parameters {
        key: "translate_x"
        node: 19
        property: "translate_x"
        group: "Armillary Composition"
    }
    parameters {
        key: "translate_y"
        node: 19
        property: "translate_y"
        group: "Armillary Composition"
    }
    parameters {
        key: "translate_z"
        node: 19
        property: "translate_z"
        group: "Armillary Composition"
    }
    parameters {
        key: "scale_x"
        node: 19
        property: "scale_x"
        group: "Armillary Composition"
    }
    parameters {
        key: "scale_y"
        node: 19
        property: "scale_y"
        group: "Armillary Composition"
    }
    parameters {
        key: "scale_z"
        node: 19
        property: "scale_z"
        group: "Armillary Composition"
    }
    title: "Armillary Composition"
}
