schema_version: 4
id: "p6-spectral-glaze"
revision: 130
nodes {
    id: 2
    type_key: "core.time"
    schema_version: 1
}
nodes {
    id: 3
    type_key: "audio.band"
    schema_version: 1
    properties {
        key: "audio_band"
        value {
            scalar: 12
        }
    }
    properties {
        key: "audio_channel"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 4
    type_key: "scalar.map"
    schema_version: 1
    properties {
        key: "input_max"
        value {
            scalar: 0.15
        }
    }
    properties {
        key: "input_min"
        value {
            scalar: 0
        }
    }
    properties {
        key: "map_mode"
        value {
            scalar: 0
        }
    }
    properties {
        key: "output_max"
        value {
            scalar: 1
        }
    }
    properties {
        key: "output_min"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 5
    type_key: "audio.band"
    schema_version: 1
    properties {
        key: "audio_band"
        value {
            scalar: 48
        }
    }
    properties {
        key: "audio_channel"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 6
    type_key: "scalar.map"
    schema_version: 1
    properties {
        key: "input_max"
        value {
            scalar: 0.15
        }
    }
    properties {
        key: "input_min"
        value {
            scalar: 0
        }
    }
    properties {
        key: "map_mode"
        value {
            scalar: 0
        }
    }
    properties {
        key: "output_max"
        value {
            scalar: 1
        }
    }
    properties {
        key: "output_min"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 7
    type_key: "audio.feature"
    schema_version: 1
    properties {
        key: "audio_feature"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 8
    type_key: "scalar.map"
    schema_version: 1
    properties {
        key: "input_max"
        value {
            scalar: 0.3
        }
    }
    properties {
        key: "input_min"
        value {
            scalar: 0
        }
    }
    properties {
        key: "map_mode"
        value {
            scalar: 0
        }
    }
    properties {
        key: "output_max"
        value {
            scalar: 0.65
        }
    }
    properties {
        key: "output_min"
        value {
            scalar: 0.15
        }
    }
}
nodes {
    id: 9
    type_key: "material.pbr"
    schema_version: 1
    properties {
        key: "color_a"
        value {
            color {
                r: 1
                g: 1
                b: 1
                a: 1
            }
        }
    }
    properties {
        key: "color_b"
        value {
            color {
                r: 0.772549033164978
                g: 0.91372549533843994
                b: 1
                a: 1
            }
        }
    }
    properties {
        key: "double_sided"
        value {
            scalar: 0
        }
    }
    properties {
        key: "emission"
        value {
            scalar: 0
        }
    }
    properties {
        key: "metallic"
        value {
            scalar: 0.25
        }
    }
    properties {
        key: "roughness"
        value {
            scalar: 0.28
        }
    }
}
nodes {
    id: 10
    type_key: "material.shader"
    schema_version: 1
    properties {
        key: "a"
        value {
            scalar: 0
        }
    }
    properties {
        key: "asset"
        value {
            asset_sha256: "d3efe6892b2ef2df98d8e96b19588812a5422a41e1217e9a211f6fd4d21e5543"
        }
    }
    properties {
        key: "b"
        value {
            scalar: 0
        }
    }
    properties {
        key: "c"
        value {
            scalar: 0
        }
    }
    properties {
        key: "d"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 11
    type_key: "geometry.sphere"
    schema_version: 1
    properties {
        key: "height"
        value {
            scalar: 1.64
        }
    }
    properties {
        key: "radial_segments"
        value {
            scalar: 96
        }
    }
    properties {
        key: "radius"
        value {
            scalar: 0.82
        }
    }
    properties {
        key: "rings"
        value {
            scalar: 48
        }
    }
}
nodes {
    id: 12
    type_key: "scene.instance"
    schema_version: 1
}
nodes {
    id: 13
    type_key: "material.pbr"
    schema_version: 1
    properties {
        key: "color_a"
        value {
            color {
                r: 0.90588235855102539
                g: 0.71764707565307617
                b: 0.45882353186607361
                a: 1
            }
        }
    }
    properties {
        key: "color_b"
        value {
            color {
                r: 1
                g: 0.79607844352722168
                b: 0.5215686559677124
                a: 1
            }
        }
    }
    properties {
        key: "double_sided"
        value {
            scalar: 0
        }
    }
    properties {
        key: "emission"
        value {
            scalar: 0
        }
    }
    properties {
        key: "metallic"
        value {
            scalar: 0.7
        }
    }
    properties {
        key: "roughness"
        value {
            scalar: 0.22
        }
    }
}
nodes {
    id: 14
    type_key: "geometry.torus"
    schema_version: 1
    properties {
        key: "radial_segments"
        value {
            scalar: 96
        }
    }
    properties {
        key: "radius"
        value {
            scalar: 1.12
        }
    }
    properties {
        key: "tube_ratio"
        value {
            scalar: 0.018
        }
    }
    properties {
        key: "tube_segments"
        value {
            scalar: 16
        }
    }
}
nodes {
    id: 15
    type_key: "scene.instance"
    schema_version: 1
}
nodes {
    id: 16
    type_key: "scene.transform"
    schema_version: 1
    properties {
        key: "rotation_x"
        value {
            scalar: 65
        }
    }
    properties {
        key: "rotation_y"
        value {
            scalar: 0
        }
    }
    properties {
        key: "rotation_z"
        value {
            scalar: 0
        }
    }
    properties {
        key: "scale"
        value {
            scalar: 1
        }
    }
    properties {
        key: "scale_x"
        value {
            scalar: 1
        }
    }
    properties {
        key: "scale_y"
        value {
            scalar: 1
        }
    }
    properties {
        key: "scale_z"
        value {
            scalar: 1
        }
    }
    properties {
        key: "translate_x"
        value {
            scalar: 0
        }
    }
    properties {
        key: "translate_y"
        value {
            scalar: 0
        }
    }
    properties {
        key: "translate_z"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 17
    type_key: "geometry.torus"
    schema_version: 1
    properties {
        key: "radial_segments"
        value {
            scalar: 96
        }
    }
    properties {
        key: "radius"
        value {
            scalar: 1.27
        }
    }
    properties {
        key: "tube_ratio"
        value {
            scalar: 0.012
        }
    }
    properties {
        key: "tube_segments"
        value {
            scalar: 16
        }
    }
}
nodes {
    id: 18
    type_key: "scene.instance"
    schema_version: 1
}
nodes {
    id: 19
    type_key: "scene.transform"
    schema_version: 1
    properties {
        key: "rotation_x"
        value {
            scalar: -55
        }
    }
    properties {
        key: "rotation_y"
        value {
            scalar: 35
        }
    }
    properties {
        key: "rotation_z"
        value {
            scalar: 0
        }
    }
    properties {
        key: "scale"
        value {
            scalar: 1
        }
    }
    properties {
        key: "scale_x"
        value {
            scalar: 1
        }
    }
    properties {
        key: "scale_y"
        value {
            scalar: 1
        }
    }
    properties {
        key: "scale_z"
        value {
            scalar: 1
        }
    }
    properties {
        key: "translate_x"
        value {
            scalar: 0
        }
    }
    properties {
        key: "translate_y"
        value {
            scalar: 0
        }
    }
    properties {
        key: "translate_z"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 20
    type_key: "scene.merge"
    schema_version: 1
}
nodes {
    id: 21
    type_key: "scene.merge"
    schema_version: 1
}
nodes {
    id: 22
    type_key: "scene.directional_light"
    schema_version: 1
    properties {
        key: "color_a"
        value {
            color {
                r: 0.90980392694473267
                g: 0.9529411792755127
                b: 1
                a: 1
            }
        }
    }
    properties {
        key: "light_energy"
        value {
            scalar: 3
        }
    }
    properties {
        key: "light_x"
        value {
            scalar: 1
        }
    }
    properties {
        key: "light_y"
        value {
            scalar: 1
        }
    }
    properties {
        key: "light_z"
        value {
            scalar: 1
        }
    }
}
nodes {
    id: 23
    type_key: "scene.merge"
    schema_version: 1
}
nodes {
    id: 25
    type_key: "scene.camera"
    schema_version: 1
    properties {
        key: "eye_x"
        value {
            scalar: 0
        }
    }
    properties {
        key: "eye_y"
        value {
            scalar: 0
        }
    }
    properties {
        key: "eye_z"
        value {
            scalar: 3
        }
    }
    properties {
        key: "far_plane"
        value {
            scalar: 1000
        }
    }
    properties {
        key: "field_of_view"
        value {
            scalar: 60
        }
    }
    properties {
        key: "near_plane"
        value {
            scalar: 0.05
        }
    }
    properties {
        key: "orthographic_height"
        value {
            scalar: 3
        }
    }
    properties {
        key: "projection"
        value {
            scalar: 1
        }
    }
    properties {
        key: "target_x"
        value {
            scalar: 0
        }
    }
    properties {
        key: "target_y"
        value {
            scalar: 0
        }
    }
    properties {
        key: "target_z"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 26
    type_key: "scene.render"
    schema_version: 1
    properties {
        key: "scene_antialiasing"
        value {
            scalar: 1
        }
    }
    properties {
        key: "texture_precision"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 27
    type_key: "output.texture"
    schema_version: 1
}
nodes {
    id: 28
    type_key: "component.user.28"
    schema_version: 1
    properties {
        key: "rotation_x"
        value {
            scalar: 0
        }
    }
    properties {
        key: "rotation_y"
        value {
            scalar: 0
        }
    }
    properties {
        key: "rotation_z"
        value {
            scalar: 0
        }
    }
    properties {
        key: "scale"
        value {
            scalar: 0.95
        }
    }
    properties {
        key: "scale_x"
        value {
            scalar: 1
        }
    }
    properties {
        key: "scale_y"
        value {
            scalar: 1.121220292519671
        }
    }
    properties {
        key: "scale_z"
        value {
            scalar: 1
        }
    }
    properties {
        key: "translate_x"
        value {
            scalar: 0
        }
    }
    properties {
        key: "translate_y"
        value {
            scalar: 0
        }
    }
    properties {
        key: "translate_z"
        value {
            scalar: 0
        }
    }
}
output: 27
canvas {
    width: 1280
    height: 720
}
signals {
    name: "n1"
    source: 2
}
signals {
    name: "n2"
    source: 3
}
signals {
    name: "n3"
    source: 4
}
signals {
    name: "n4"
    source: 5
}
signals {
    name: "n5"
    source: 6
}
signals {
    name: "n6"
    source: 7
}
signals {
    name: "n7"
    source: 8
}
signals {
    name: "n8"
    source: 9
}
signals {
    name: "n9"
    source: 10
}
signals {
    name: "n10"
    source: 11
}
signals {
    name: "n11"
    source: 12
}
signals {
    name: "n12"
    source: 13
}
signals {
    name: "n13"
    source: 14
}
signals {
    name: "n14"
    source: 15
}
signals {
    name: "n15"
    source: 16
}
signals {
    name: "n16"
    source: 17
}
signals {
    name: "n17"
    source: 18
}
signals {
    name: "n18"
    source: 19
}
signals {
    name: "n19"
    source: 20
}
signals {
    name: "n20"
    source: 21
}
signals {
    name: "n21"
    source: 22
}
signals {
    name: "n22"
    source: 23
}
signals {
    name: "n23"
    source: 28
}
signals {
    name: "n24"
    source: 25
}
signals {
    name: "n25"
    source: 26
}
signals {
    name: "n26"
    source: 27
}
bindings {
    node: 4
    input: "value"
    signal: "n2"
}
bindings {
    node: 6
    input: "value"
    signal: "n4"
}
bindings {
    node: 8
    input: "value"
    signal: "n6"
}
bindings {
    node: 9
    input: "emission"
    signal: "n7"
}
bindings {
    node: 10
    input: "a"
    signal: "n3"
}
bindings {
    node: 10
    input: "b"
    signal: "n5"
}
bindings {
    node: 10
    input: "material"
    signal: "n8"
}
bindings {
    node: 10
    input: "time"
    signal: "n1"
}
bindings {
    node: 12
    input: "geometry"
    signal: "n10"
}
bindings {
    node: 12
    input: "material"
    signal: "n9"
}
bindings {
    node: 13
    input: "emission"
    signal: "n7"
}
bindings {
    node: 15
    input: "geometry"
    signal: "n13"
}
bindings {
    node: 15
    input: "material"
    signal: "n12"
}
bindings {
    node: 16
    input: "rotation_y"
    signal: "n1"
}
bindings {
    node: 16
    input: "scene"
    signal: "n14"
}
bindings {
    node: 18
    input: "geometry"
    signal: "n16"
}
bindings {
    node: 18
    input: "material"
    signal: "n12"
}
bindings {
    node: 19
    input: "rotation_z"
    signal: "n1"
}
bindings {
    node: 19
    input: "scene"
    signal: "n17"
}
bindings {
    node: 20
    input: "a"
    signal: "n15"
}
bindings {
    node: 20
    input: "b"
    signal: "n18"
}
bindings {
    node: 21
    input: "a"
    signal: "n11"
}
bindings {
    node: 21
    input: "b"
    signal: "n19"
}
bindings {
    node: 23
    input: "a"
    signal: "n20"
}
bindings {
    node: 23
    input: "b"
    signal: "n21"
}
bindings {
    node: 28
    input: "scene"
    signal: "n22"
}
bindings {
    node: 26
    input: "camera"
    signal: "n24"
}
bindings {
    node: 26
    input: "scene"
    signal: "n23"
}
bindings {
    node: 27
    input: "source"
    signal: "n25"
}
components {
    type_key: "component.user.28"
    schema_version: 1
    nodes {
        id: 24
        type_key: "scene.transform"
        schema_version: 1
        properties {
            key: "rotation_x"
            value {
                scalar: 0
            }
        }
        properties {
            key: "rotation_y"
            value {
                scalar: 0
            }
        }
        properties {
            key: "rotation_z"
            value {
                scalar: 0
            }
        }
        properties {
            key: "scale"
            value {
                scalar: 0.95
            }
        }
        properties {
            key: "scale_x"
            value {
                scalar: 1
            }
        }
        properties {
            key: "scale_y"
            value {
                scalar: 1.121220292519671
            }
        }
        properties {
            key: "scale_z"
            value {
                scalar: 1
            }
        }
        properties {
            key: "translate_x"
            value {
                scalar: 0
            }
        }
        properties {
            key: "translate_y"
            value {
                scalar: 0
            }
        }
        properties {
            key: "translate_z"
            value {
                scalar: 0
            }
        }
    }
    output: 24
    signals {
        name: "n23"
        source: 24
    }
    inputs {
        key: "scene"
        node: 24
        input: "scene"
    }
    parameters {
        key: "rotation_x"
        node: 24
        property: "rotation_x"
        group: "Glaze Composition"
    }
    parameters {
        key: "rotation_y"
        node: 24
        property: "rotation_y"
        group: "Glaze Composition"
    }
    parameters {
        key: "rotation_z"
        node: 24
        property: "rotation_z"
        group: "Glaze Composition"
    }
    parameters {
        key: "scale"
        node: 24
        property: "scale"
        group: "Glaze Composition"
    }
    parameters {
        key: "translate_x"
        node: 24
        property: "translate_x"
        group: "Glaze Composition"
    }
    parameters {
        key: "translate_y"
        node: 24
        property: "translate_y"
        group: "Glaze Composition"
    }
    parameters {
        key: "translate_z"
        node: 24
        property: "translate_z"
        group: "Glaze Composition"
    }
    parameters {
        key: "scale_x"
        node: 24
        property: "scale_x"
        group: "Glaze Composition"
    }
    parameters {
        key: "scale_y"
        node: 24
        property: "scale_y"
        group: "Glaze Composition"
    }
    parameters {
        key: "scale_z"
        node: 24
        property: "scale_z"
        group: "Glaze Composition"
    }
    title: "Glaze Composition"
}
