add_library(particles STATIC simulation.cpp)
target_include_directories(particles PUBLIC include)
rhythm_project_target(particles)
if(BUILD_TESTING)
    add_executable(particle_simulation_tests tests/simulation_tests.cpp)
    target_link_libraries(particle_simulation_tests PRIVATE particles)
    rhythm_project_target(particle_simulation_tests)
    add_test(NAME particle_simulation COMMAND particle_simulation_tests)
endif()
