schema_version: 4
id: "p5-vector-resonance"
revision: 118
nodes {
    id: 2
    type_key: "core.time"
    schema_version: 1
}
nodes {
    id: 3
    type_key: "audio.band"
    schema_version: 1
    properties {
        key: "audio_band"
        value {
            scalar: 12
        }
    }
    properties {
        key: "audio_channel"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 4
    type_key: "scalar.map"
    schema_version: 1
    properties {
        key: "input_max"
        value {
            scalar: 0.15
        }
    }
    properties {
        key: "input_min"
        value {
            scalar: 0
        }
    }
    properties {
        key: "map_mode"
        value {
            scalar: 0
        }
    }
    properties {
        key: "output_max"
        value {
            scalar: 1.16
        }
    }
    properties {
        key: "output_min"
        value {
            scalar: 0.92
        }
    }
}
nodes {
    id: 5
    type_key: "audio.band"
    schema_version: 1
    properties {
        key: "audio_band"
        value {
            scalar: 48
        }
    }
    properties {
        key: "audio_channel"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 6
    type_key: "scalar.map"
    schema_version: 1
    properties {
        key: "input_max"
        value {
            scalar: 0.1
        }
    }
    properties {
        key: "input_min"
        value {
            scalar: 0
        }
    }
    properties {
        key: "map_mode"
        value {
            scalar: 0
        }
    }
    properties {
        key: "output_max"
        value {
            scalar: 16
        }
    }
    properties {
        key: "output_min"
        value {
            scalar: 3
        }
    }
}
nodes {
    id: 7
    type_key: "scalar.map"
    schema_version: 1
    properties {
        key: "input_max"
        value {
            scalar: 60
        }
    }
    properties {
        key: "input_min"
        value {
            scalar: 0
        }
    }
    properties {
        key: "map_mode"
        value {
            scalar: 0
        }
    }
    properties {
        key: "output_max"
        value {
            scalar: 3600
        }
    }
    properties {
        key: "output_min"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 8
    type_key: "path.helix"
    schema_version: 1
    properties {
        key: "path_closed"
        value {
            scalar: 1
        }
    }
    properties {
        key: "path_height"
        value {
            scalar: 0
        }
    }
    properties {
        key: "path_phase"
        value {
            scalar: 0
        }
    }
    properties {
        key: "path_radius"
        value {
            scalar: 1.2
        }
    }
    properties {
        key: "path_samples"
        value {
            scalar: 192
        }
    }
    properties {
        key: "path_turns"
        value {
            scalar: 1
        }
    }
}
nodes {
    id: 9
    type_key: "path.helix"
    schema_version: 1
    properties {
        key: "path_closed"
        value {
            scalar: 1
        }
    }
    properties {
        key: "path_height"
        value {
            scalar: 0
        }
    }
    properties {
        key: "path_phase"
        value {
            scalar: 0
        }
    }
    properties {
        key: "path_radius"
        value {
            scalar: 0.84
        }
    }
    properties {
        key: "path_samples"
        value {
            scalar: 192
        }
    }
    properties {
        key: "path_turns"
        value {
            scalar: 1
        }
    }
}
nodes {
    id: 10
    type_key: "texture.path_fill"
    schema_version: 1
    properties {
        key: "color_a"
        value {
            color {
                r: 0.20392157137393951
                g: 0.88235294818878174
                b: 0.800000011920929
                a: 1
            }
        }
    }
    properties {
        key: "path_plane"
        value {
            scalar: 1
        }
    }
    properties {
        key: "path_samples"
        value {
            scalar: 512
        }
    }
    properties {
        key: "path_span"
        value {
            scalar: 4
        }
    }
    properties {
        key: "texture_precision"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 11
    type_key: "path.helix"
    schema_version: 1
    properties {
        key: "path_closed"
        value {
            scalar: 0
        }
    }
    properties {
        key: "path_height"
        value {
            scalar: 0
        }
    }
    properties {
        key: "path_phase"
        value {
            scalar: 0
        }
    }
    properties {
        key: "path_radius"
        value {
            scalar: 1.4
        }
    }
    properties {
        key: "path_samples"
        value {
            scalar: 192
        }
    }
    properties {
        key: "path_turns"
        value {
            scalar: 0.82
        }
    }
}
nodes {
    id: 12
    type_key: "texture.path_stroke"
    schema_version: 1
    properties {
        key: "color_a"
        value {
            color {
                r: 1
                g: 0.82352942228317261
                b: 0.54117649793624878
                a: 1
            }
        }
    }
    properties {
        key: "path_plane"
        value {
            scalar: 1
        }
    }
    properties {
        key: "path_samples"
        value {
            scalar: 512
        }
    }
    properties {
        key: "path_span"
        value {
            scalar: 4
        }
    }
    properties {
        key: "texture_precision"
        value {
            scalar: 0
        }
    }
    properties {
        key: "vector_cap"
        value {
            scalar: 2
        }
    }
    properties {
        key: "vector_join"
        value {
            scalar: 2
        }
    }
    properties {
        key: "vector_miter"
        value {
            scalar: 4
        }
    }
    properties {
        key: "vector_tolerance"
        value {
            scalar: 0.25
        }
    }
    properties {
        key: "vector_width"
        value {
            scalar: 4
        }
    }
}
nodes {
    id: 13
    type_key: "path.helix"
    schema_version: 1
    properties {
        key: "path_closed"
        value {
            scalar: 0
        }
    }
    properties {
        key: "path_height"
        value {
            scalar: 2.8
        }
    }
    properties {
        key: "path_phase"
        value {
            scalar: 0
        }
    }
    properties {
        key: "path_radius"
        value {
            scalar: 0.48
        }
    }
    properties {
        key: "path_samples"
        value {
            scalar: 192
        }
    }
    properties {
        key: "path_turns"
        value {
            scalar: 2.5
        }
    }
}
nodes {
    id: 14
    type_key: "texture.path_stroke"
    schema_version: 1
    properties {
        key: "color_a"
        value {
            color {
                r: 0.9529411792755127
                g: 0.49019607901573181
                b: 0.72549021244049072
                a: 1
            }
        }
    }
    properties {
        key: "path_plane"
        value {
            scalar: 0
        }
    }
    properties {
        key: "path_samples"
        value {
            scalar: 512
        }
    }
    properties {
        key: "path_span"
        value {
            scalar: 4
        }
    }
    properties {
        key: "texture_precision"
        value {
            scalar: 0
        }
    }
    properties {
        key: "vector_cap"
        value {
            scalar: 2
        }
    }
    properties {
        key: "vector_join"
        value {
            scalar: 2
        }
    }
    properties {
        key: "vector_miter"
        value {
            scalar: 4
        }
    }
    properties {
        key: "vector_tolerance"
        value {
            scalar: 0.25
        }
    }
    properties {
        key: "vector_width"
        value {
            scalar: 3
        }
    }
}
nodes {
    id: 15
    type_key: "texture.composite"
    schema_version: 1
    properties {
        key: "amount"
        value {
            scalar: 1
        }
    }
    properties {
        key: "composite_mode"
        value {
            scalar: 0
        }
    }
    properties {
        key: "texture_precision"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 16
    type_key: "texture.composite"
    schema_version: 1
    properties {
        key: "amount"
        value {
            scalar: 1
        }
    }
    properties {
        key: "composite_mode"
        value {
            scalar: 0
        }
    }
    properties {
        key: "texture_precision"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 17
    type_key: "texture.blur"
    schema_version: 1
    properties {
        key: "blur_radius"
        value {
            scalar: 16
        }
    }
    properties {
        key: "texture_precision"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 18
    type_key: "texture.composite"
    schema_version: 1
    properties {
        key: "amount"
        value {
            scalar: 1
        }
    }
    properties {
        key: "composite_mode"
        value {
            scalar: 0
        }
    }
    properties {
        key: "texture_precision"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 19
    type_key: "texture.noise"
    schema_version: 1
    properties {
        key: "color_a"
        value {
            color {
                r: 0.0117647061124444
                g: 0.027450980618596077
                b: 0.074509806931018829
                a: 1
            }
        }
    }
    properties {
        key: "color_b"
        value {
            color {
                r: 0.062745101749897
                g: 0.16470588743686676
                b: 0.19215686619281769
                a: 1
            }
        }
    }
    properties {
        key: "contrast"
        value {
            scalar: 1
        }
    }
    properties {
        key: "noise_scale"
        value {
            scalar: 3
        }
    }
    properties {
        key: "phase"
        value {
            scalar: 0
        }
    }
    properties {
        key: "seed"
        value {
            scalar: 0
        }
    }
    properties {
        key: "texture_precision"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 20
    type_key: "texture.composite"
    schema_version: 1
    properties {
        key: "amount"
        value {
            scalar: 1
        }
    }
    properties {
        key: "composite_mode"
        value {
            scalar: 0
        }
    }
    properties {
        key: "texture_precision"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 21
    type_key: "texture.fxaa"
    schema_version: 1
    properties {
        key: "fxaa_reduce_minimum"
        value {
            scalar: 0.0078125
        }
    }
    properties {
        key: "fxaa_reduce_multiplier"
        value {
            scalar: 0.125
        }
    }
    properties {
        key: "fxaa_span"
        value {
            scalar: 8
        }
    }
    properties {
        key: "fxaa_strength"
        value {
            scalar: 1
        }
    }
    properties {
        key: "texture_precision"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 22
    type_key: "texture.affine"
    schema_version: 1
    properties {
        key: "opacity"
        value {
            scalar: 1
        }
    }
    properties {
        key: "pivot_x"
        value {
            scalar: 0.5
        }
    }
    properties {
        key: "pivot_y"
        value {
            scalar: 0.5
        }
    }
    properties {
        key: "rotation"
        value {
            scalar: 0
        }
    }
    properties {
        key: "scale"
        value {
            scalar: 0.95
        }
    }
    properties {
        key: "scale_x"
        value {
            scalar: 1
        }
    }
    properties {
        key: "scale_y"
        value {
            scalar: 1
        }
    }
    properties {
        key: "texture_precision"
        value {
            scalar: 0
        }
    }
    properties {
        key: "translate_x"
        value {
            scalar: 0
        }
    }
    properties {
        key: "translate_y"
        value {
            scalar: 0
        }
    }
}
nodes {
    id: 24
    type_key: "output.texture"
    schema_version: 1
}
nodes {
    id: 25
    type_key: "component.user.25"
    schema_version: 1
    properties {
        key: "opacity"
        value {
            scalar: 1
        }
    }
    properties {
        key: "pivot_x"
        value {
            scalar: 0.5
        }
    }
    properties {
        key: "pivot_y"
        value {
            scalar: 0.5
        }
    }
    properties {
        key: "rotation"
        value {
            scalar: 0
        }
    }
    properties {
        key: "scale"
        value {
            scalar: 1
        }
    }
    properties {
        key: "scale_x"
        value {
            scalar: 1
        }
    }
    properties {
        key: "scale_y"
        value {
            scalar: 1
        }
    }
    properties {
        key: "texture_precision"
        value {
            scalar: 0
        }
    }
    properties {
        key: "translate_x"
        value {
            scalar: 0
        }
    }
    properties {
        key: "translate_y"
        value {
            scalar: 0
        }
    }
}
output: 24
canvas {
    width: 1280
    height: 720
}
signals {
    name: "n1"
    source: 2
}
signals {
    name: "n2"
    source: 3
}
signals {
    name: "n3"
    source: 4
}
signals {
    name: "n4"
    source: 5
}
signals {
    name: "n5"
    source: 6
}
signals {
    name: "n6"
    source: 7
}
signals {
    name: "n7"
    source: 8
}
signals {
    name: "n8"
    source: 9
}
signals {
    name: "n9"
    source: 10
}
signals {
    name: "n10"
    source: 11
}
signals {
    name: "n11"
    source: 12
}
signals {
    name: "n12"
    source: 13
}
signals {
    name: "n13"
    source: 14
}
signals {
    name: "n14"
    source: 15
}
signals {
    name: "n15"
    source: 16
}
signals {
    name: "n16"
    source: 17
}
signals {
    name: "n17"
    source: 18
}
signals {
    name: "n18"
    source: 19
}
signals {
    name: "n19"
    source: 20
}
signals {
    name: "n20"
    source: 21
}
signals {
    name: "n21"
    source: 22
}
signals {
    name: "n22"
    source: 25
}
signals {
    name: "n23"
    source: 24
}
bindings {
    node: 4
    input: "value"
    signal: "n2"
}
bindings {
    node: 6
    input: "value"
    signal: "n4"
}
bindings {
    node: 7
    input: "value"
    signal: "n1"
}
bindings {
    node: 8
    input: "path_radius"
    signal: "n3"
}
bindings {
    node: 10
    input: "hole"
    signal: "n8"
}
bindings {
    node: 10
    input: "path"
    signal: "n7"
}
bindings {
    node: 11
    input: "path_phase"
    signal: "n6"
}
bindings {
    node: 12
    input: "path"
    signal: "n10"
}
bindings {
    node: 12
    input: "vector_width"
    signal: "n5"
}
bindings {
    node: 13
    input: "path_phase"
    signal: "n6"
}
bindings {
    node: 14
    input: "path"
    signal: "n12"
}
bindings {
    node: 15
    input: "a"
    signal: "n9"
}
bindings {
    node: 15
    input: "b"
    signal: "n11"
}
bindings {
    node: 16
    input: "a"
    signal: "n14"
}
bindings {
    node: 16
    input: "b"
    signal: "n13"
}
bindings {
    node: 17
    input: "source"
    signal: "n15"
}
bindings {
    node: 18
    input: "a"
    signal: "n16"
}
bindings {
    node: 18
    input: "b"
    signal: "n15"
}
bindings {
    node: 19
    input: "phase"
    signal: "n1"
}
bindings {
    node: 20
    input: "a"
    signal: "n18"
}
bindings {
    node: 20
    input: "b"
    signal: "n17"
}
bindings {
    node: 21
    input: "source"
    signal: "n19"
}
bindings {
    node: 22
    input: "source"
    signal: "n20"
}
bindings {
    node: 25
    input: "source"
    signal: "n21"
}
bindings {
    node: 24
    input: "source"
    signal: "n22"
}
components {
    type_key: "component.user.25"
    schema_version: 1
    nodes {
        id: 23
        type_key: "texture.affine"
        schema_version: 1
        properties {
            key: "opacity"
            value {
                scalar: 1
            }
        }
        properties {
            key: "pivot_x"
            value {
                scalar: 0.5
            }
        }
        properties {
            key: "pivot_y"
            value {
                scalar: 0.5
            }
        }
        properties {
            key: "rotation"
            value {
                scalar: 0
            }
        }
        properties {
            key: "scale"
            value {
                scalar: 1
            }
        }
        properties {
            key: "scale_x"
            value {
                scalar: 1
            }
        }
        properties {
            key: "scale_y"
            value {
                scalar: 1
            }
        }
        properties {
            key: "texture_precision"
            value {
                scalar: 0
            }
        }
        properties {
            key: "translate_x"
            value {
                scalar: 0
            }
        }
        properties {
            key: "translate_y"
            value {
                scalar: 0
            }
        }
    }
    output: 23
    signals {
        name: "n22"
        source: 23
    }
    inputs {
        key: "source"
        node: 23
        input: "source"
    }
    parameters {
        key: "scale"
        node: 23
        property: "scale"
        group: "Vector Composition"
    }
    parameters {
        key: "scale_x"
        node: 23
        property: "scale_x"
        group: "Vector Composition"
    }
    parameters {
        key: "scale_y"
        node: 23
        property: "scale_y"
        group: "Vector Composition"
    }
    parameters {
        key: "rotation"
        node: 23
        property: "rotation"
        group: "Vector Composition"
    }
    parameters {
        key: "translate_x"
        node: 23
        property: "translate_x"
        group: "Vector Composition"
    }
    parameters {
        key: "translate_y"
        node: 23
        property: "translate_y"
        group: "Vector Composition"
    }
    parameters {
        key: "pivot_x"
        node: 23
        property: "pivot_x"
        group: "Vector Composition"
    }
    parameters {
        key: "pivot_y"
        node: 23
        property: "pivot_y"
        group: "Vector Composition"
    }
    parameters {
        key: "opacity"
        node: 23
        property: "opacity"
        group: "Vector Composition"
    }
    parameters {
        key: "texture_precision"
        node: 23
        property: "texture_precision"
        group: "Vector Composition"
    }
    title: "Vector Composition"
}
