add_library(physics2d STATIC world.cpp joints.cpp contacts.cpp)
target_include_directories(physics2d PUBLIC include)
target_link_libraries(physics2d PRIVATE box2d::box2d)
rhythm_project_target(physics2d)
if(BUILD_TESTING)
    add_executable(physics2d_tests tests/world_tests.cpp)
    target_link_libraries(physics2d_tests PRIVATE physics2d)
    rhythm_project_target(physics2d_tests)
    add_test(NAME physics2d COMMAND physics2d_tests)
endif()
