add_library(performance STATIC list.cpp)
target_include_directories(performance PUBLIC include)
target_link_libraries(performance PUBLIC parameters asset_types)
rhythm_project_target(performance)
if(BUILD_TESTING)
    add_executable(performance_list_tests tests/list_tests.cpp)
    target_link_libraries(performance_list_tests PRIVATE performance)
    rhythm_project_target(performance_list_tests)
    add_test(NAME performance_list COMMAND performance_list_tests)
endif()
