set(rhythm_deps "${PROJECT_SOURCE_DIR}/third_party/sources")
set(SDL_SHARED ON CACHE BOOL "" FORCE)
set(SDL_STATIC OFF CACHE BOOL "" FORCE)
set(SDL_TEST_LIBRARY OFF CACHE BOOL "" FORCE)
set(SDL_TESTS OFF CACHE BOOL "" FORCE)
set(SDL_RENDER OFF CACHE BOOL "" FORCE)
set(SDL_GPU OFF CACHE BOOL "" FORCE)
add_subdirectory("${rhythm_deps}/sdl" "${PROJECT_BINARY_DIR}/deps/sdl" EXCLUDE_FROM_ALL)
add_library(spike_bx STATIC "${rhythm_deps}/bx/src/amalgamated.cpp")
target_include_directories(spike_bx SYSTEM PUBLIC "${rhythm_deps}/bx/include")
target_include_directories(spike_bx PRIVATE "${rhythm_deps}/bx/3rdparty")
add_library(spike_bimg STATIC "${rhythm_deps}/bimg/src/image.cpp")
target_include_directories(spike_bimg SYSTEM PUBLIC "${rhythm_deps}/bimg/include")
target_compile_definitions(spike_bimg PRIVATE BIMG_CONFIG_DECODE_ASTC=0)
target_link_libraries(spike_bimg PRIVATE spike_bx)
add_library(spike_bgfx STATIC "${rhythm_deps}/bgfx/src/amalgamated.cpp")
target_include_directories(spike_bgfx SYSTEM PUBLIC "${rhythm_deps}/bgfx/include")
target_include_directories(spike_bgfx PRIVATE "${rhythm_deps}/bgfx/3rdparty" "${rhythm_deps}/bgfx/3rdparty/khronos")
target_compile_definitions(spike_bgfx PRIVATE
    BGFX_CONFIG_RENDERER_DIRECT3D11=0 BGFX_CONFIG_RENDERER_DIRECT3D12=0
    BGFX_CONFIG_RENDERER_OPENGL=0 BGFX_CONFIG_RENDERER_OPENGLES=30
    BGFX_CONFIG_RENDERER_VULKAN=0 BGFX_CONFIG_RENDERER_WEBGPU=0
    BGFX_CONFIG_MULTITHREADED=0 BGFX_CONFIG_VIDEO=0)
target_link_libraries(spike_bgfx PRIVATE spike_bx spike_bimg EGL GLESv3 android log)
foreach(target spike_bx spike_bimg spike_bgfx)
    target_compile_features(${target} PRIVATE cxx_std_20)
    target_compile_definitions(${target} PRIVATE BX_CONFIG_DEBUG=0)
endforeach()
add_library(render_bgfx STATIC "${PROJECT_SOURCE_DIR}/src/rhythm_render/src/bgfx_backend.cpp")
target_include_directories(render_bgfx PRIVATE "${PROJECT_SOURCE_DIR}/src/rhythm_render/src"
    "${rhythm_deps}/bgfx/examples/common/imgui")
target_link_libraries(render_bgfx PRIVATE Rhythm::Render spike_bgfx spike_bx)
target_compile_definitions(render_bgfx PRIVATE BX_CONFIG_DEBUG=0)
rhythm_project_target(render_bgfx)
include("${PROJECT_SOURCE_DIR}/cmake/RenderShaders.cmake")
