if(WIN32)
    set(RHYTHM_IO_SDK "${PROJECT_SOURCE_DIR}/../vcpkg/installed/x64-windows" CACHE PATH "Read-only codec SDK")
else()
    set(RHYTHM_IO_SDK "" CACHE PATH "Target-platform Protobuf and JSON SDK")
endif()
if(RHYTHM_IO_SDK)
    list(PREPEND CMAKE_PREFIX_PATH "${RHYTHM_IO_SDK}")
endif()
# Cross builds must provide a host executable, never run target protoc.
if(CMAKE_CROSSCOMPILING)
    set(RHYTHM_PROTOC "" CACHE FILEPATH "Host protoc matching the target Protobuf version")
    if(NOT EXISTS "${RHYTHM_PROTOC}")
        message(FATAL_ERROR "Set RHYTHM_PROTOC to a matching host protoc")
    endif()
    set(Protobuf_PROTOC_EXECUTABLE "${RHYTHM_PROTOC}" CACHE FILEPATH "Host protobuf compiler" FORCE)
endif()
find_package(Protobuf CONFIG REQUIRED)
find_package(nlohmann_json CONFIG REQUIRED)
if(NOT CMAKE_CROSSCOMPILING)
    set(RHYTHM_PROTOC "$<TARGET_FILE:protobuf::protoc>")
endif()
